// Boss mothership — 40x32 grid, scale 2 = 80x64px
// Menacing capital ship with cannons and eye core
export const BOSS_SHIP = [
	"                   MM                    ",
	"                  MMMM                   ",
	"                 MMnnMM                  ",
	"                MMMnnMMM                 ",
	"              MMMMnnnMMMM                ",
	"             MMMMMnnMMMMMM               ",
	"           nMMMMMMnnMMMMMMn              ",
	"          nMMMMMMMnnMMMMMMMn             ",
	"        nMMMMMMMMMnnMMMMMMMMMn           ",
	"      nnMMMMMMMMMMMMMMMMMMMMMnn          ",
	"     nMMMMMMMMMMMMMMMMMMMMMMMMn          ",
	"    nMMMMMMMnnnnnnnnnnnMMMMMMMn         ",
	"   nMMMMMMMn           nMMMMMMMn        ",
	"  nMMMMMMMMn   WWWWW   nMMMMMMMMn       ",
	" nMMMMMMMMMn  WWWWWWW  nMMMMMMMMMn      ",
	"nMMMMMMMMMMn  WWMWMWW  nMMMMMMMMMMn     ",
	" nMMMMMMMMMn  WWWWWWW  nMMMMMMMMMn      ",
	"  nMMMMMMMMn   WWWWW   nMMMMMMMMn       ",
	"   nMMMMMMMn           nMMMMMMMn        ",
	"    nMMMMMMMnnnnnnnnnnnMMMMMMMn         ",
	"     nMMMMMMMMMMMMMMMMMMMMMMMMn          ",
	"      nnMMMMMMMMMMMMMMMMMMMMMnn          ",
	"       nMMMMMRRMMMMMRRMMMMMn            ",
	"        nMMMRRRMMMMMRRRMMMn             ",
	"         nMMRRMMMMMMRRMMn               ",
	"          nnMMMMMMMMMMMMnn               ",
	"            nMMMMMMMMMMn                 ",
	"             nnMMMMMMnn                  ",
	"               nnMMnn                    ",
	"                 nn                      ",
	"                nMMn                     ",
	"                 nn                      ",
];

// Boss enraged — same shape but with red accents
export const BOSS_ENRAGED = [
	"                   RR                    ",
	"                  RMMR                   ",
	"                 MMnnMM                  ",
	"                MMMnnMMM                 ",
	"              MMMMnnnMMMM                ",
	"             MMMMMnnMMMMMM               ",
	"           nMMMMMMnnMMMMMMn              ",
	"          nMMMMMMMnnMMMMMMMn             ",
	"        nMMMMMMMMMnnMMMMMMMMMn           ",
	"      nnMMMMMMMMMMMMMMMMMMMMMnn          ",
	"     nMMMMMMMMMMMMMMMMMMMMMMMMn          ",
	"    nMMMMMMMnnnnnnnnnnnMMMMMMMn         ",
	"   nMMMMMMMn           nMMMMMMMn        ",
	"  nMMMMMMMMn   RRRRR   nMMMMMMMMn       ",
	" nMMMMMMMMMn  RRRRRRR  nMMMMMMMMMn      ",
	"nMMMMMMMMMMn  RRMRMRR  nMMMMMMMMMMn     ",
	" nMMMMMMMMMn  RRRRRRR  nMMMMMMMMMn      ",
	"  nMMMMMMMMn   RRRRR   nMMMMMMMMn       ",
	"   nMMMMMMMn           nMMMMMMMn        ",
	"    nMMMMMMMnnnnnnnnnnnMMMMMMMn         ",
	"     nMMMMMMMMMMMMMMMMMMMMMMMMn          ",
	"      nnMMMMMMMMMMMMMMMMMMMMMnn          ",
	"       nMMMMMRRMMMMMRRMMMMMn            ",
	"        nMMMRRRMMMMMRRRMMMn             ",
	"         nMMRRMMMMMMRRMMn               ",
	"          nnMMMMMMMMMMMMnn               ",
	"            nMMMMMMMMMMn                 ",
	"             nnMMMMMMnn                  ",
	"               nnMMnn                    ",
	"                 nn                      ",
	"                nRRn                     ",
	"                 RR                      ",
];
